[package]
name = "netservices"
version = "0.1.0"
edition = "2021"

[dependencies]
amplify = "4.0.0-beta.1"
re-actor = { path = "re-actor", optional = true }
io-reactor = { path = "io-reactor", optional = true }
cyphernet = { version = "0.1.0", features = ["ed25519", "pem"] }
mio = { version = "0.8.5", optional = true }
socket2 = { version = "0.4.7", optional = true }
libc = "0.2.138"

[dev-dependencies]
cyphernet = { version = "0.1.0", features = ["ed25519", "rand"] }
bitcoin_hashes = "0.11.0"
log = "0.4.17"

[features]
default = ["io-reactor", "socket2"]

[patch.crates-io]
cyphernet = { git = "https://github.com/Cyphernet-WG/rust-cyphernet" }
[workspace]
members = ["re-actor", "io-reactor", "nsh"]
default-members = ["io-reactor"]
exclude = ["node"]
