[package]
name = "netservices"
version = "0.1.0"
edition = "2021"

[dependencies]
reactor = { path = "re-actor", package = "re-actor" }
streampipes = { path = "streampipes" }
cyphernet = { git = "https://github.com/Internet2-WG/rust-cyphernet", features = ["ed25519"] }

[dev-dependencies]
amplify = "3.13.0"
cyphernet = { git = "https://github.com/Internet2-WG/rust-cyphernet", features = ["ed25519", "rand"] }
bitcoin_hashes = "0.11.0"
log = "0.4.17"

[workspace]
members = ["poll-reactor", "streampipes", "nsh", "node"]
default-members = ["re-actor", "poll-reactor", "streampipes", "node"]
