[package]
name = "node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amplify = "3.13.0"
crossbeam-channel = "0.5.6"
io-reactor = { path = "../io-reactor" }
